-- AVTOMATIK YARATILGAN — qoʻlda tahrirlamang.
-- Manba: blue_wolf_darajalar.xlsx, “Sozlamalar” varagʻi.
-- Qayta yaratish: python3 tools/blue_wolf_config.py

USE bluewolf;

INSERT INTO game_config (config_key, config_value, unit, note) VALUES
  ('xp_base', 80, 'XP', 'Boshlangʻich daraja narxi'),
  ('xp_growth', 1.38, 'x', 'Har daraja oldingisidan shuncha qimmat'),
  ('stat_power_base', 12, 'ball', '1-daraja kuchi'),
  ('stat_power_growth', 1.2, 'x', 'Har darajada'),
  ('stat_speed_base', 10, 'ball', '1-daraja tezligi'),
  ('stat_speed_growth', 1.13, 'x', 'Har darajada'),
  ('stat_hp_base', 60, 'HP', '1-daraja jon miqdori'),
  ('stat_hp_growth', 1.18, 'x', 'Har darajada'),
  ('class_real', 1, 'x', '1–19 daraja'),
  ('class_ancient', 1.35, 'x', '20–21 daraja'),
  ('class_myth', 1.8, 'x', '22–25 daraja'),
  ('pack_unlock_level', 4, 'daraja', 'Shu darajadan toʻda, klan va PvP ochiladi'),
  ('stage_early', 0.4, 'x', '1–4 daraja: XP, narx va vaqt shunga koʻpaytiriladi'),
  ('stage_mid', 0.7, 'x', '5–10 daraja'),
  ('stage_mid_level', 10, 'daraja', 'Shu darajagacha oʻrta koeffitsient'),
  ('stage_normal', 1, 'x', '11–15 daraja'),
  ('stage_late', 1.25, 'x', '16+ daraja: ataylab qiyinlashadi'),
  ('stage_late_level', 15, 'daraja', 'Shundan keyin kech bosqich'),
  ('tutorial_end_level', 5, 'daraja', 'Shu darajada qoʻllanma tugaydi'),
  ('tutorial_target_min', 15, 'daqiqa', 'Boshidan tugashigacha'),
  ('tutorial_free_speedups', 5, 'marta', 'Tanishtiruvda qurilish darhol tugaydi'),
  ('tutorial_skip_step', 12, 'qadam', 'Shundan keyin «Oʻtkazib yuborish» tugmasi chiqadi'),
  ('quest_daily_count', 4, 'ta', 'Har kuni yangilanadi'),
  ('quest_weekly_count', 4, 'ta', 'Har dushanba yangilanadi'),
  ('quest_daily_cap', 0.15, 'ulush', 'Kunlik ishlab chiqarishdan — hammasi qoʻshib'),
  ('quest_weekly_cap', 0.4, 'ulush', 'Bir kunlik ishlab chiqarishdan'),
  ('quest_milestone_cap', 0.5, 'ulush', 'Bir martalik, kunlik ishlab chiqarishdan'),
  ('quest_speedup_min', 10, 'daqiqa', 'Vazifa uchun beriladigan tezlashtirish'),
  ('quest_safe_cap', 0.6, 'ulush', 'Barcha vazifa mukofoti kunlik ishlab chiqarishdan oshmasin'),
  ('train_meat_base', 20, 'kg', '1-tier askar yigʻish'),
  ('train_bone_base', 8, 'birlik', '1-tier askar yigʻish'),
  ('train_time_min', 4, 'daqiqa', '1-tier askar yigʻish'),
  ('promote_loss', 0.1, 'ulush', 'Kuch konversiyasida yoʻqoladigan ulush'),
  ('promote_cost_share', 0.6, 'x', 'Yangi askar narxiga nisbatan'),
  ('promote_time_share', 0.5, 'x', 'Yangi askar vaqtiga nisbatan'),
  ('occupancy_normal', 0.6, 'ulush', 'Shu nuqtada vaqt koeffitsienti 1.00'),
  ('occupancy_exp', 1.8, 'daraja', 'Qanchalik keskin oʻzgarishi'),
  ('occupancy_min', 0.5, 'x', 'Qoʻshin juda kam boʻlganda chegirma'),
  ('train_coef_max', 5, 'x', 'Bino jazosi bilan birga eng koʻpi'),
  ('offline_store_mult', 2, 'x', 'Oʻyinchi yoʻqligida ombor sigʻimi shuncha oshadi'),
  ('offline_prod_rate', 0.7, 'ulush', 'Oflaynda ishlab chiqarish shuncha qismda ishlaydi'),
  ('hunger_cp_penalty', 0.3, 'ulush', 'Ochlikda jangovar quvvat shuncha tushadi'),
  ('hunger_prod_penalty', 0.5, 'ulush', 'Ochlikda ishlab chiqarish shuncha tushadi'),
  ('hunger_leave_after_d', 7, 'kun', 'Shundan keyin askarlar asta ketadi'),
  ('hunger_leave_daily', 0.01, 'ulush', 'Har kuni shuncha askar ketadi'),
  ('hunger_leave_max', 0.5, 'ulush', 'Ochlikdan koʻpi bilan shuncha yoʻqoladi'),
  ('sleep_shield_h', 72, 'soat', 'Shundan keyin avtomatik qalqon yoqiladi'),
  ('comeback_shield_min', 30, 'daqiqa', 'Kirgandan keyin qalqon shuncha turadi'),
  ('speedup_daily_cap', 0.25, 'ulush', 'Kunlik progressning shunchasidan koʻpini sotib boʻlmaydi'),
  ('speedup_base_price', 10, 'oy toshi/soat', 'Birinchi blok narxi'),
  ('speedup_price_growth', 1.6, 'x', 'Har keyingi blok shuncha qimmat'),
  ('speedup_block_h', 1, 'soat', 'Narx bloki'),
  ('moonstone_per_usd', 100, 'oy toshi/$', '1 dollarga nechta oy toshi'),
  ('price_season_pass', 500, 'oy toshi', 'Battle pass'),
  ('price_second_queue', 1500, 'oy toshi', '4–9 darajada erta ochish; 10-darajadan bepul'),
  ('return_price_coef', 0.6, 'x', 'Qaytish tezlashtirishi arzonroq'),
  ('return_speedup_max', 1, 'ulush', 'Qaytish vaqtining shunchasini qisqartirish mumkin'),
  ('vacation_delay_h', 12, 'soat', 'Yoqilgandan keyin shuncha vaqtdan soʻng ishga tushadi'),
  ('vacation_min_h', 24, 'soat', 'Undan qisqa boʻlmaydi'),
  ('vacation_max_h', 168, 'soat', '7 kun'),
  ('vacation_free_h', 48, 'soat/oy', 'Oyiga bir marta bepul'),
  ('vacation_price_day', 250, 'oy toshi/kun', 'Bepul muddatdan keyin'),
  ('match_offers', 9, 'ta', 'Server tasodifiy tanlaydi'),
  ('match_refresh_min', 30, 'daqiqa', 'Yoki 3 ta hujumdan keyin'),
  ('battle_base_loss', 0.4, 'ulush', 'Teng kuchda yoʻqotiladigan askar'),
  ('battle_max_loss', 0.9, 'ulush', 'Bir jangda eng koʻp yoʻqotish'),
  ('battle_rounds', 5, 'raund', 'Har raundda ikki tomon zarba beradi'),
  ('battle_variance', 0.1, 'ulush', 'Zarar ±shuncha tebranadi'),
  ('att_death_share', 0.4, 'ulush', 'Yoʻqotilganlarning shunchasi oʻladi'),
  ('def_death_share', 0.25, 'ulush', 'Uyda — Shifo gʻori yaqin'),
  ('march_speed', 20, 'km/soat', 'Eng sekin askar tezligi'),
  ('scout_speed', 60, 'km/soat', 'Razvedkachi 3 barobar tez'),
  ('war_duration_h', 12, 'soat', 'Ochilgandan yopilgunicha'),
  ('war_power_window', 0.2, 'ulush', 'Faqat ±shuncha kuchdagi klanlar taklif etiladi'),
  ('war_min_participation', 0.25, 'ulush', 'Klan kuchining shunchasi yuborilishi shart'),
  ('war_min_members', 0.4, 'ulush', 'Aʼzolarning shunchasi qatnashishi shart'),
  ('war_repeat_block_d', 7, 'kun', 'Bir juftlik shu muddat ichida qayta urusholmaydi'),
  ('war_deposit', 0.05, 'ulush', 'Klan xazinasidan garovga qoʻyiladi'),
  ('war_winner_loss', 0.2, 'ulush', 'Yuborilgan askarlardan'),
  ('war_loser_loss', 0.4, 'ulush', 'Yuborilgan askarlardan'),
  ('war_winner_death_share', 0.3, 'ulush', 'Yoʻqotilganlardan oʻladigan qismi'),
  ('war_loser_death_share', 0.45, 'ulush', 'Yoʻqotilganlardan oʻladigan qismi'),
  ('war_member_cap', 0.15, 'ulush', 'Bitta aʼzo urush fondidan koʻpi bilan'),
  ('war_loser_reward_share', 0.25, 'ulush', 'Gʻolib mukofotiga nisbatan'),
  ('clan_xp_base', 5000, 'XP', '1-darajadan keyingi daraja uchun'),
  ('clan_xp_growth', 1.32, 'x', 'Kerakli klan XP = baza × shu^(daraja−1)'),
  ('pack_solo_size', 1, 'bosh', '1–3 daraja: oʻyinchi yolgʻiz'),
  ('pack_base', 10, 'askar', 'Toʻda ochilgan darajada (4-daraja)'),
  ('pack_growth', 1.2, 'x', 'Har darajada koʻpaytiriladi'),
  ('cp_w_power', 2, 'x', 'Jangovar quvvat formulasida'),
  ('cp_w_speed', 1.5, 'x', 'Jangovar quvvat formulasida'),
  ('cp_w_hp', 0.5, 'x', 'Jangovar quvvat formulasida'),
  ('need_base', 0.6, 'kg/askar', '1-darajali askar bir kunda'),
  ('need_growth', 0.1, 'kg/daraja', 'Har darajada qoʻshiladi'),
  ('water_need_base', 0.4, 'birlik/askar', '1-darajada'),
  ('water_need_growth', 0.04, 'birlik/daraja', 'Har darajada'),
  ('moonlight_need', 0.2, 'birlik/boʻri', 'Faqat 20+ daraja'),
  ('reserve_days', 3, 'kun', 'Ombor shuncha kunlik oziqni sigʻdirishi kerak'),
  ('store_base', 40, 'kg', '1-daraja'),
  ('store_growth', 1.22, 'x', 'Har darajada — qoʻshin oʻsishiga moslangan'),
  ('water_passive_base', 0.25, 'birlik/soat', 'Gʻor oʻzi yigʻadi'),
  ('water_passive_growth', 1.25, 'x', 'Har darajada — suv ehtiyojiga moslangan (~2×)'),
  ('cave_protect_base', 0.3, 'ulush', 'Reyddan saqlanadigan zaxira'),
  ('cave_protect_growth', 0.02, 'ulush/daraja', 'Har darajada'),
  ('cost_food_cave_stone', 100, 'birlik', '1→2 daraja uchun'),
  ('cost_food_cave_wood', 60, 'birlik', '1→2 daraja uchun'),
  ('prod_base', 20, 'birlik/soat', 'Jami qurilish resursi'),
  ('prod_growth', 1.22, 'x', 'Har darajada — narx oʻsishidan (1.30) past boʻlishi shart'),
  ('workshop_buffer_h', 10, 'soat', 'Bufer = soatlik ishlab chiqarish × shu; qurilish resurslari ombori cheklanmagan'),
  ('cost_workshop_stone', 150, 'birlik', '1→2 daraja uchun'),
  ('cost_workshop_wood', 100, 'birlik', '1→2 daraja uchun'),
  ('cost_workshop_bone', 40, 'birlik', '1→2 daraja uchun'),
  ('cost_growth', 1.3, 'x', 'Har darajada (25 daraja uchun moslangan)'),
  ('time_growth', 1.25, 'x', 'Har darajada (25 daraja uchun moslangan)'),
  ('build_time_base_min', 10, 'daqiqa', '1→2 daraja uchun'),
  ('build_plan_days', 7, 'kun', 'Keyingi darajaga resurs toʻplash muddati'),
  ('alpha_bonus', 0.03, 'ulush/daraja', 'Askar statiga qoʻshiladi (25-darajada +75%)'),
  ('tier_coef', 1.45, 'x', 'Har tierda stat shuncha oshadi'),
  ('tier_step_level', 4, 'daraja', 'Maks tier = MAX(1, MIN(6, alfa darajasi ÷ shu, bino ÷ shu))'),
  ('counter_bonus', 1.3, 'x', 'Uchburchakda ustunlik'),
  ('sample_alpha_level', 19, 'daraja', 'Quyidagi CP jadvali shu darajaga hisoblangan'),
  ('share_scout', 0.2, 'ulush', 'Tavsiya etilgan slot ulushi'),
  ('share_attacker', 0.45, 'ulush', 'Tavsiya etilgan slot ulushi'),
  ('share_defender', 0.2, 'ulush', 'Tavsiya etilgan slot ulushi'),
  ('share_hunter', 0.15, 'ulush', 'Eng kamida 1 ta ovchi doim boʻladi'),
  ('tier_step_building', 4, 'daraja', 'Har 4 daraja = 1 tier ochiladi'),
  ('building_level_over_player', 0, 'daraja', 'Bino alfa darajasidan oshmaydi — maks daraja = oʻyinchi darajasi'),
  ('cost_role_stone', 180, 'birlik', '1→2 daraja'),
  ('cost_role_bone', 90, 'birlik', '1→2 daraja'),
  ('cost_role_hide', 150, 'birlik', '1→2 daraja'),
  ('train_speed_per_level', 0.04, 'ulush/daraja', 'Mashq vaqtini qisqartiradi'),
  ('cost_coef_scout_rock', 0.5, 'x', 'Bazaviy maydon narxiga nisbatan'),
  ('cost_coef_battle_ground', 0.7, 'x', 'Eng qimmat — hujumchi asosiy rol'),
  ('cost_coef_defense_wall', 0.6, 'x', 'Bazaviy maydon narxiga nisbatan'),
  ('cost_coef_hunt_path', 0.45, 'x', 'Eng arzon — boshidan kerak boʻladi'),
  ('camp_rate', 0.1, 'x', 'Bir boʻri = Ustaxona soatlik ishlab chiqarishining shuncha qismi'),
  ('camp_tier_bonus', 0.05, 'ulush/tier', 'Yuqori tier tezroq yigʻadi'),
  ('camp_hours', 8, 'soat', 'Shundan keyin toʻda inga qaytadi'),
  ('camp_send_share', 0.5, 'ulush', 'Toʻdaning eng koʻpi shuncha qismi'),
  ('oasis_count', 20, 'ta', 'Cheklangan — shuning uchun urush sababi'),
  ('oasis_bonus_water', 0.12, 'ulush', 'Suv oazisi; boshqa oazislar bonusi oazis jadvalida'),
  ('oasis_hold_h', 24, 'soat', 'Egallangandan keyin hujum qilib boʻlmaydi'),
  ('role_cap_base', 6, 'ta', 'Bino 1-darajada nechta askar sigʻadi'),
  ('role_cap_growth', 1.2, 'x', 'Har bino darajasida koʻpaytiriladi'),
  ('role_cap_penalty_exp', 2, 'daraja', 'Vaqt koeffitsienti = toʻlganlik ^ shu'),
  ('role_cap_penalty_max', 5, 'x', 'Mashq vaqti shundan koʻp choʻzilmaydi'),
  ('time_coef_food_cave', 1, 'x', 'Bazaviy qurilish vaqtiga nisbatan'),
  ('time_coef_workshop', 1.2, 'x', 'Asosiy iqtisod binosi — sekinroq'),
  ('time_coef_scout_rock', 0.8, 'x', 'Yengil qurilish'),
  ('time_coef_battle_ground', 1.3, 'x', 'Eng sekin — asosiy PvP binosi'),
  ('time_coef_defense_wall', 1.1, 'x', 'Ogʻir qurilish'),
  ('time_coef_hunt_path', 0.7, 'x', 'Eng tez — boshidan kerak'),
  ('time_coef_hospital', 0.9, 'x', 'Bazaviy qurilish vaqtiga nisbatan'),
  ('time_coef_market', 1, 'x', 'Bazaviy qurilish vaqtiga nisbatan'),
  ('hospital_cap_base', 2, 'boʻri', 'Bir vaqtda nechta jarohatlangan boʻri davolanadi'),
  ('hospital_cap_growth', 0.4, 'boʻri/daraja', 'Har darajada'),
  ('heal_time_min', 60, 'daqiqa', 'Bitta boʻri, 1-darajada'),
  ('heal_speed_growth', 0.05, 'ulush/daraja', 'Vaqtni qisqartiradi'),
  ('cost_hospital_wood', 120, 'birlik', '1→2 daraja'),
  ('cost_hospital_hide', 100, 'birlik', '1→2 daraja'),
  ('cost_hospital_stone', 80, 'birlik', '1→2 daraja'),
  ('market_rate_base', 3, 'x', '1-darajada 3 birlik berib 1 olasiz'),
  ('market_rate_step', 0.075, 'x/daraja', 'Har darajada kurs yaxshilanadi'),
  ('market_limit_base', 200, 'birlik', 'Kuniga almashtirish mumkin boʻlgan miqdor'),
  ('market_limit_growth', 1.2, 'x', 'Har darajada'),
  ('market_tax_base', 0.2, 'ulush', 'Almashinuvdan ushlanadi'),
  ('market_tax_step', 0.006, 'ulush/daraja', 'Har darajada'),
  ('cost_market_stone', 130, 'birlik', '1→2 daraja'),
  ('cost_market_wood', 110, 'birlik', '1→2 daraja'),
  ('fund_dau_estimate', 10000, 'ta', 'Kunlik faol oʻyinchi (DAU)'),
  ('fund_arpu_estimate', 0.05, '$', 'Bitta oʻyinchidan kunlik daromad'),
  ('fund_share', 0.15, 'ulush', 'Daromadning shuncha qismi sovrin fondiga'),
  ('season_days', 7, 'kun', 'Reyting shundan keyin nolga tushadi'),
  ('season_player_cap', 0.05, 'ulush', 'Bitta oʻyinchi fondning shuncha qismidan koʻp ololmaydi'),
  ('season_min_battles', 5, 'ta', 'Shundan kam jang qilgan mukofot olmaydi'),
  ('season_final_days_mult', 1.5, 'x', 'Mavsumning oxirgi 3 kunida hissa'),
  ('coins_per_usd', 1000, 'tanga/$', 'Oʻyin ichidagi tanga qiymati'),
  ('season_new_account_d', 14, 'kun', 'Shundan keyin mukofotga kira oladi'),
  ('fair_pair_season_limit', 3, 'jang', 'Bir juftlikning mavsumda hisobga olinadigan janglari'),
  ('fair_closed_group_share', 0.6, 'ulush', 'Janglarning shuncha qismi bir guruh ichida boʻlsa — bayroq'),
  ('fair_closed_group_size', 5, 'oʻyinchi', 'Shuncha kishilik guruh tekshiriladi'),
  ('fair_min_defense_cp', 0.6, 'ulush', 'Himoyachi inida shuncha kuch turishi shart'),
  ('fair_min_rounds', 3, 'raund', 'Jang shundan qisqa boʻlsa — hissa 0'),
  ('fair_min_att_loss', 0.15, 'ulush', 'Hujumchi shuncha askar yoʻqotishi kerak'),
  ('fair_one_sided_ratio', 10, 'x', 'Zarar nisbati shundan yuqori boʻlsa koeff. tushadi'),
  ('fair_clan_switch_d', 7, 'kun', 'Toʻda almashtirgan shu muddat mukofotsiz'),
  ('fair_payout_wait_h', 48, 'soat', 'Mavsum tugagach tekshiruv muddati'),
  ('fair_manual_top', 100, 'oʻyinchi', 'Top shuncha profil qoʻlda koʻriladi'),
  ('loot_carry_base', 15, 'kg/hujumchi', 'Bitta hujumchi olib keta oladigan miqdor'),
  ('loot_carry_tier', 0.2, 'ulush/tier', 'Yuqori tier koʻproq olib ketadi'),
  ('loot_cap_ratio', 0.5, 'ulush', 'Reyd daromadi kunlik ovdan shuncha oshmasin'),
  ('raid_coef', 0.22, 'ulush', 'Himoyalanmagan zaxiradan olinadigan ulush'),
  ('attack_window_down', 1, 'daraja', 'Shuncha past darajaga hujum qilish mumkin'),
  ('attack_window_up', 1, 'daraja', 'Shuncha yuqori darajaga hujum qilish mumkin'),
  ('shield_newbie_level', 6, 'daraja', 'Shu darajagacha umuman hujum qilib boʻlmaydi'),
  ('window_expand_min', 30, 'daqiqa', 'Mos raqib topilmasa, oyna shuncha vaqtdan keyin kengayadi'),
  ('window_max', 3, 'daraja', 'Oyna eng koʻpi bilan shuncha kengayadi'),
  ('window_min_pool', 10, 'oʻyinchi', 'Oynada shuncha faol raqib boʻlishi kerak'),
  ('scout_partial', 1, 'x', 'Shundan past — razvedka muvaffaqiyatsiz'),
  ('scout_full', 1.5, 'x', 'Askar soni va oʻlja koʻrinadi'),
  ('scout_exact', 2.5, 'x', 'Aniq raqamlar va himoya foizi koʻrinadi'),
  ('scout_cooldown_min', 10, 'daqiqa', 'Keyingi razvedkagacha'),
  ('scout_report_min', 30, 'daqiqa', 'Shundan keyin maʼlumot eskiradi'),
  ('scout_fail_injury', 0.1, 'ulush', 'Yoʻqotilgan razvedkachilar ulushi'),
  ('scout_loot_accuracy', 0.2, 'ulush', 'Toʻliq bosqichda raqam ±shuncha xato koʻrsatiladi'),
  ('revenge_bonus', 0.2, 'ulush', '24 soat ichida qaytarilgan hujumga'),
  ('xp_hunt_coef', 0.5, 'xp/kg', 'Oʻlja vazni × shu'),
  ('xp_build_coef', 0.02, 'xp/birlik', 'Sarflangan qurilish resursi × shu'),
  ('xp_pvp_coef', 0.03, 'xp/EP', 'Yetkazilgan EP zarar × shu × natija koeff.'),
  ('xp_pvp_win', 1.5, 'x', 'Natija koeffitsienti'),
  ('xp_pvp_draw', 1, 'x', 'Natija koeffitsienti'),
  ('xp_pvp_loss', 0.5, 'x', 'Natija koeffitsienti'),
  ('xp_quest_share', 0.1, 'ulush', 'Vazifa mukofot byudjetining shunchasi XP sifatida'),
  ('catchup_max_mult', 0.5, 'ulush', '+50% gacha'),
  ('catchup_gap_coef', 1.5, 'x', '(nisbat − chegara) × shu'),
  ('catchup_gap_threshold', 0.3, 'ulush', 'Shundan kam orqada qolganga bonus yoʻq'),
  ('catchup_taper_start', 15, 'daraja', 'Bonus shu darajadan pasayadi'),
  ('catchup_taper_end', 20, 'daraja', 'Shu darajada bonus 0'),
  ('hunter_unlock_level', 3, 'daraja', 'Ov soʻqmogʻi bilan'),
  ('solo_hunt_max_level', 3, 'daraja', '1–3 darajada alfa oʻzi ovlaydi'),
  ('solo_hunt_cooldown_min', 2, 'daqiqa', 'Bosishlar orasida'),
  ('hunt_duration_min', 60, 'daqiqa', 'Balans hisobi: ovchi kuniga 4 marta shuncha vaqt ovda (ov xaritasi kartalari 16–85 daqiqa)'),
  ('hunter_yield_mult', 5, 'x', 'Ovchi unumi (kg/soat) = shu × bir askarning kunlik ehtiyoji'),
  ('hunter_tier_bonus', 0.1, 'ulush/tier', 'Yuqori tier ovchi koʻproq ovlaydi'),
  ('prey_kg_per_wolf', 20, 'kg/boʻri', 'Minimal toʻda = oʻlja vazni ÷ shu (yuqoriga)'),
  ('hunt_small_party_penalty', 0.3, 'x', 'Toʻda yetmasa ov natijasi × shu'),
  ('hunt_board_refresh_h', 4, 'soat', '9 ta ov kartasi shu oraliqda yangilanadi (har oʻyinchida har xil)'),
  ('hunt_base_min', 10, 'daqiqa', 'Ov vaqti = shu + borib-kelish yoʻli'),
  ('hunt_herb_share', 0.1, 'ulush', 'Ov natijasining shunchasi oʻt (birlik)'),
  ('moonlight_need_level', 20, 'daraja', 'Shu darajadan oy nuri kerak'),
  ('moonlight_passive_base', 0.006, 'birlik/askar/soat', 'Ehtiyojning 72%'),
  ('moon_altar_bonus', 0.4, 'ulush', 'Passiv oy nuriga qoʻshiladi (72% → 100%)'),
  ('moonlight_cp_penalty', 0.15, 'ulush', 'Goʻsht ochligidan alohida'),
  ('market_moonlight_mult', 2, 'x', 'Oy nuri boshqa resursdan shuncha qimmat'),
  ('thirst_speed_penalty', 0.2, 'ulush', 'Yurish tezligi shuncha kamayadi'),
  ('heal_herb_per_tier', 2, 'birlik/tier', 'Bir boʻri uchun'),
  ('heal_no_hospital_min', 180, 'daqiqa', '1–5 daraja: bepul, sekin'),
  ('battle_full_win_r', 1.5, 'R', 'R shundan katta yoki teng'),
  ('battle_win_r', 1.1, 'R', 'Qisman gʻalaba shundan'),
  ('battle_loss_r', 0.9, 'R', 'R shundan kichik yoki teng — magʻlubiyat; oraliq — durang'),
  ('trap_chance', 0.15, 'ulush', 'Razvedkasiz hujumda'),
  ('trap_damage', 0.2, 'ulush', 'Hujumchi yoʻqotishiga qoʻshiladi'),
  ('retreat_loss', 0.8, 'ulush', 'Yoʻqotish shundan oshsa jang 4-raundda tugaydi'),
  ('wall_bonus_per_level', 0.01, 'ulush/daraja', 'Himoyachi EP si'),
  ('pair_limit', 3, 'ta', '24 soat ichida'),
  ('loot_partial_win', 0.55, 'x', 'Toʻliq gʻalaba — 1.00'),
  ('loot_repeat_2', 0.5, 'x', '24 soat ichida'),
  ('loot_repeat_3', 0.25, 'x', '24 soat ichida'),
  ('loot_level_m1', 0.7, 'x', 'Pastga hujum'),
  ('loot_level_p1', 1.3, 'x', 'Yuqoriga hujum'),
  ('loot_level_m2', 0.5, 'x', 'Kengaygan oyna'),
  ('loot_level_p2', 1.5, 'x', 'Kengaygan oyna'),
  ('loot_level_m3', 0.3, 'x', 'Kengaygan oyna'),
  ('loot_level_p3', 1.7, 'x', 'Kengaygan oyna'),
  ('loot_offline_mult', 0.5, 'x', 'Himoyachi 24+ soat oflayn boʻlsa'),
  ('loot_offline_after_h', 24, 'soat', 'Shundan uzoq oflayn'),
  ('bot_unlock_level', 4, 'daraja', '4–6 darajada roʻyxat faqat botlardan'),
  ('bot_power_weak', 0.7, 'x', 'Oʻyinchi EP siga nisbatan'),
  ('bot_power_even', 1, 'x', 'Oʻyinchi EP siga nisbatan'),
  ('bot_power_strong', 1.3, 'x', 'Oʻyinchi EP siga nisbatan'),
  ('bot_variance', 0.1, 'ulush', '±shuncha'),
  ('queue_cancel_refund', 0.8, 'ulush', 'Navbat bekor qilinsa resursning shunchasi qaytadi'),
  ('second_queue_free_level', 10, 'daraja', 'Shu darajadan hammaga'),
  ('offline_store_plus', 0.5, 'x', 'Oflayn koeffitsientga qoʻshiladi (2.0 → 2.5)'),
  ('offline_after_min', 5, 'daqiqa', 'Oxirgi soʻrovdan shuncha oʻtsa — oflayn'),
  ('den_speed_coef', 0.01, 'ulush/daraja', 'In darajasi boshiga'),
  ('camp_yield_share_max', 0.6, 'ulush', 'Ustaxona kunlik ishlab chiqarishiga nisbatan'),
  ('shield_after_raid_loss', 0.3, 'ulush', 'Shundan koʻp yoʻqotgan himoyachiga qalqon'),
  ('shield_after_raid_h', 8, 'soat', '30%+ yoʻqotgandan keyin'),
  ('shield_two_losses_h', 16, 'soat', 'Ketma-ket 2 magʻlubiyatdan keyin'),
  ('tutorial_speedup_min', 60, 'daqiqa', 'Har bir bepul tezlashtirish'),
  ('war_decline_penalty', 50, 'reyting', 'Klan reytingidan'),
  ('night_raid_speed_bonus', 0.25, 'ulush', '22-darajadan, 22:00–06:00'),
  ('hunt_speed_kmh', 40, 'km/soat', 'Borib-kelish: 2 × masofa ÷ shu'),
  ('hunt_km_min', 2, 'km', 'Yaqin kartalar (xavfsiz) shundan boshlanadi'),
  ('hunt_km_near_max', 7, 'km', '1–3-kartalar: 2–7 km, xavf yoʻq'),
  ('hunt_km_mid_max', 15, 'km', '4–6-kartalar: 7–15 km'),
  ('hunt_km_far_max', 25, 'km', '7–9-kartalar: 15–25 km (eng uzoq ov ~85 daqiqa)'),
  ('hunt_mid_bonus', 0.2, 'ulush', 'Oʻrta masofada oʻlja koʻproq — xavf evaziga'),
  ('hunt_far_bonus', 0.5, 'ulush', 'Uzoq masofada'),
  ('hunt_mid_injury', 0.08, 'ehtimol', 'Har bir yuborilgan boʻri uchun'),
  ('hunt_far_injury', 0.15, 'ehtimol', 'Har bir yuborilgan boʻri uchun'),
  ('hunt_mid_death', 0.01, 'ehtimol', 'Har bir yuborilgan boʻri uchun'),
  ('hunt_far_death', 0.04, 'ehtimol', 'Har bir yuborilgan boʻri uchun'),
  ('hunt_herd_min', 0.7, 'x', 'Poda = tavsiya etilgan ovchilar unumi × shu…'),
  ('hunt_herd_spread', 0.9, 'x', '… + tasodifiy 0–shu (kartaga qarab)'),
  ('quest_monthly_count', 3, 'ta', 'Har oy (kalendar oy) 3 ta vazifa'),
  ('quest_monthly_cap', 0.6, 'ulush', 'Oylik vazifalar jami = kunlik ishlab chiqarish × shu'),
  ('quest_daily_chest', 0.05, 'ulush', 'Kunning hamma vazifasi bajarilganda (× kombo koeff.)'),
  ('quest_combo_step', 0.1, 'ulush/kun', 'Ketma-ket har kun uchun sandiq +shu'),
  ('quest_combo_max_days', 7, 'kun', 'Shundan keyin oʻsmaydi (maks ×1.6)'),
  ('quest_weekly_chest', 0.1, 'ulush', 'Haftaning hamma vazifasi bajarilganda'),
  ('quest_monthly_chest', 0.3, 'ulush', 'Oyning hamma vazifasi bajarilganda'),
  ('login_gift_step', 0.01, 'ulush/kun', '7 kunlik taqvim: n-kun = shu × n'),
  ('quest_meat_ratio', 2, 'x', 'Goʻsht mukofoti = ulush × shu × toʻdaning kunlik goʻsht ehtiyoji'),
  ('quest_tz_offset_h', 5, 'soat', 'Kun/hafta/oy chegarasi: UTC+shu (Toshkent)')
AS new ON DUPLICATE KEY UPDATE
  config_value = new.config_value, unit = new.unit, note = new.note;
